Try new release tag

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -56,3 +56,32 @@ jobs:
       - name: Publish
         run: |
           yarn lerna publish from-git --yes --allowBranch=main --loglevel=verbose --dist-tag latest
+
+      - name: Push Release Tag
+        run: |
+          git config user.name ${{ github.actor }}
+          git config user.email ${{ github.actor }}@users.noreply.github.com
+
+          commit=${{ github.sha }}
+          if ! n=$(git rev-list --count $commit~ --since="00:00"); then
+              echo 'failed to calculate tag'
+              exit 1
+          fi
+
+          case "$n" in
+              0) suffix="" ;; # first commit of the day gets no suffix
+              *) suffix=".$n" ;; # subsequent commits get a suffix, starting with .1
+          esac
+
+          tag=$(printf release-$(date '+%Y-%m-%d%%s') $suffix)
+
+          git tag -a $tag -m "Release $tag"
+          git push origin $tag
+
+      - name: Create Release
+        id: create-release
+        uses: actions/github-script@v7
+        with:
+          script: |
+            const script = require('./scripts/create-github-release.js')
+            await script({github, context, core, exec})
